sonar.projectKey=user-crud-jenkins
sonar.projectName=User CRUD Jenkins Pipeline
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,junit.xml,security-reports/**,monitoring-reports/**,build-info/**,Dockerfile,docker-compose.yml,prometheus.yml,alert.rules.yml

sonar.tests=tests
sonar.test.inclusions=tests/**/*.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info